# Generated by Django 4.1.3 on 2023-03-18 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expert_interests',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='expert_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interests', models.CharField(max_length=1000)),
                ('links', models.CharField(max_length=1000)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.expert')),
            ],
        ),
    ]
