# Generated by Django 4.1.3 on 2023-03-26 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0002_expert_expert_interests_alter_expert_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expert_interests',
            field=models.JSONField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='expert',
            unique_together={('user', 'expert_id')},
        ),
    ]
