# Generated by Django 4.1.3 on 2023-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_expert_expert_interests_alter_expert_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expert_thumbnail',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
